# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/exec.preprocess_vits.ipynb (unless otherwise specified).

__all__ = []

# Cell
import argparse

from ..text.util import batch_clean_text, clean_text
from ..utils.utils import load_filepaths_and_text

try:
    from nbdev.imports import IN_NOTEBOOK
except:
    IN_NOTEBOOK = False

if __name__ == "__main__" and not IN_NOTEBOOK:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out_extension", default="cleaned")
    parser.add_argument("--text_index", default=1, type=int)
    parser.add_argument(
        "--filelists",
        nargs="+",
        default=[
            "filelists/ljs_audio_text_val_filelist.txt",
            "filelists/ljs_audio_text_test_filelist.txt",
        ],
    )
    parser.add_argument(
        "--text_cleaners", nargs="+", default=["english_cleaners_phonemizer"]
    )

    args = parser.parse_args()

    for filelist in args.filelists:
        print("START:", filelist)
        filepaths_and_text = load_filepaths_and_text(filelist)
        text_batch = [fat[args.text_index] for fat in filepaths_and_text]
        cleaned_text_batch = batch_clean_text(text_batch, args.text_cleaners)

        for i in range(len(filepaths_and_text)):
            filepaths_and_text[i][args.text_index] = cleaned_text_batch[i]

        new_filelist = filelist + "." + args.out_extension
        with open(new_filelist, "w", encoding="utf-8") as f:
            f.writelines(["|".join(x) + "\n" for x in filepaths_and_text])