# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.exec.ipynb (unless otherwise specified).

__all__ = ['parse_args', 'parse_args']

# Cell
import argparse
import sys

# Cell
def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", help="Path to JSON config")
    args = parser.parse_args(args)
    return args

# Cell
import argparse
import sys

# Cell
def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", help="Path to JSON config")
    args = parser.parse_args(args)
    return args