# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.plot.ipynb (unless otherwise specified).

__all__ = ['mel_spectrogram', 'plot_attention']

# Cell
import matplotlib
import matplotlib.pyplot as plt

def mel_spectrogram(mel):
    figure = plt.figure()
    plt.xlabel("Spectrogram frame")
    plt.ylabel("Channel")
    plt.imshow(mel, aspect="auto", origin="lower", interpolation="none", cmap="inferno")
    return figure

# Cell

def plot_attention(attention):
    figure = plt.figure()
    plt.xlabel("Decoder timestep")
    plt.ylabel("Encoder timestep")
    plt.imshow(
        attention.data.cpu().numpy(),
        aspect="auto",
        origin="lower",
        interpolation="none",
        cmap="inferno",
    )
    return figure