# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://uberduck-ai.github.io/uberduck_ml_dev/"

git_url = "https://github.com/uberduck-ai/uberduck_ml_dev/tree/master/"

def custom_doc_links(name):
    return None
