# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TTSModel": "models.base.ipynb",
         "Tacotron2": "models.mellotron.ipynb",
         "TTSTrainer": "trainer.base.ipynb",
         "load_filepaths_and_text": "utils.ipynb",
         "synthesize_speakerids2": "utils.ipynb",
         "parse_vctk": "utils.ipynb",
         "parse_libritts_mellotron": "utils.ipynb",
         "flac_to_wav": "utils.ipynb",
         "add_speakerid": "utils.ipynb",
         "parse_uberduck": "utils.ipynb",
         "parse_lj7": "utils.ipynb"}

modules = ["models/base.py",
           "models/mellotron.py",
           "trainer/base.py",
           "utils.py"]

doc_url = "https://uberduck-ai.github.io/uberduck_ml_dev/"

git_url = "https://github.com/uberduck-ai/uberduck_ml_dev/tree/master/"

def custom_doc_links(name): return None
