# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/data_loader.ipynb (unless otherwise specified).

__all__ = ['TextMelDataset', 'TextMelCollate']

# Cell
import os
import random
import re
from typing import List

import numpy as np
import torch
from torch.utils.data import Dataset

from .models.common import STFT
from .text.util import text_to_sequence

# Cell


class TextMelDataset(Dataset):
    def __init__(
        self,
        dataset_path: str,
        audiopaths_and_text: str,
        text_cleaners: List[str],
        n_mel_channels: int,
        mel_fmin: float,
        mel_fmax: float,
    ):
        pass


class TextMelCollate:
    def __init__(self, n_frames_per_step):
        self.n_frames_per_step = n_frames_per_step

    def __call__(self, batch):
        pass