name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install espeak libsndfile-dev
      - name: Install the library
        run: |
          pip install -e .
      - name: Run tests
        run: |
          python -m pytest
